# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 14) do

  create_table "authors", :force => true do |t|
    t.column "first_name", :string
    t.column "last_name", :string
  end

  create_table "authors_books", :id => false, :force => true do |t|
    t.column "author_id", :integer, :default => 0, :null => false
    t.column "book_id", :integer, :default => 0, :null => false
  end

  add_index "authors_books", ["author_id"], :name => "authors_books_author_id_index"
  add_index "authors_books", ["book_id"], :name => "authors_books_book_id_index"

  create_table "books", :force => true do |t|
    t.column "title", :string, :default => "", :null => false
    t.column "publisher_id", :integer, :default => 0, :null => false
    t.column "published_at", :datetime
    t.column "isbn", :string, :limit => 13
    t.column "blurb", :text
    t.column "page_count", :integer
    t.column "price", :float
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
    t.column "cover_image", :string
    t.column "blurb_html", :text
  end

  create_table "books_tags", :id => false, :force => true do |t|
    t.column "tag_id", :integer, :default => 0, :null => false
    t.column "book_id", :integer, :default => 0, :null => false
  end

  add_index "books_tags", ["tag_id"], :name => "fk_tb_tags"
  add_index "books_tags", ["book_id"], :name => "fk_tb_books"

  create_table "cart_items", :force => true do |t|
    t.column "book_id", :integer
    t.column "cart_id", :integer
    t.column "price", :float
    t.column "amount", :integer
    t.column "created_at", :datetime
  end

  create_table "carts", :force => true do |t|
  end

  create_table "forum_posts", :force => true do |t|
    t.column "name", :string, :limit => 50, :default => "", :null => false
    t.column "subject", :string, :default => "", :null => false
    t.column "body", :text
    t.column "root_id", :integer, :default => 0, :null => false
    t.column "parent_id", :integer, :default => 0, :null => false
    t.column "lft", :integer, :default => 0, :null => false
    t.column "rgt", :integer, :default => 0, :null => false
    t.column "depth", :integer, :default => 0, :null => false
    t.column "created_at", :datetime, :null => false
    t.column "updated_at", :datetime, :null => false
  end

  create_table "globalize_countries", :force => true do |t|
    t.column "code", :string, :limit => 2
    t.column "english_name", :string
    t.column "date_format", :string
    t.column "currency_format", :string
    t.column "currency_code", :string, :limit => 3
    t.column "thousands_sep", :string, :limit => 2
    t.column "decimal_sep", :string, :limit => 2
    t.column "currency_decimal_sep", :string, :limit => 2
    t.column "number_grouping_scheme", :string
  end

  add_index "globalize_countries", ["code"], :name => "globalize_countries_code_index"

  create_table "globalize_languages", :force => true do |t|
    t.column "iso_639_1", :string, :limit => 2
    t.column "iso_639_2", :string, :limit => 3
    t.column "iso_639_3", :string, :limit => 3
    t.column "rfc_3066", :string
    t.column "english_name", :string
    t.column "english_name_locale", :string
    t.column "english_name_modifier", :string
    t.column "native_name", :string
    t.column "native_name_locale", :string
    t.column "native_name_modifier", :string
    t.column "macro_language", :boolean
    t.column "direction", :string
    t.column "pluralization", :string
    t.column "scope", :string, :limit => 1
  end

  add_index "globalize_languages", ["iso_639_1"], :name => "globalize_languages_iso_639_1_index"
  add_index "globalize_languages", ["iso_639_2"], :name => "globalize_languages_iso_639_2_index"
  add_index "globalize_languages", ["iso_639_3"], :name => "globalize_languages_iso_639_3_index"
  add_index "globalize_languages", ["rfc_3066"], :name => "globalize_languages_rfc_3066_index"

  create_table "globalize_translations", :force => true do |t|
    t.column "type", :string
    t.column "tr_key", :string
    t.column "table_name", :string
    t.column "item_id", :integer
    t.column "facet", :string
    t.column "built_in", :boolean, :default => true
    t.column "language_id", :integer
    t.column "pluralization_index", :integer
    t.column "text", :text
  end

  add_index "globalize_translations", ["tr_key", "language_id"], :name => "globalize_translations_tr_key_index"
  add_index "globalize_translations", ["table_name", "item_id", "language_id"], :name => "globalize_translations_table_name_index"

  create_table "order_items", :force => true do |t|
    t.column "book_id", :integer
    t.column "order_id", :integer
    t.column "price", :float
    t.column "amount", :integer
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

  create_table "orders", :force => true do |t|
    t.column "email", :string
    t.column "phone_number", :string
    t.column "ship_to_first_name", :string
    t.column "ship_to_last_name", :string
    t.column "ship_to_address", :string
    t.column "ship_to_city", :string
    t.column "ship_to_postal_code", :string
    t.column "ship_to_country", :string
    t.column "customer_ip", :string
    t.column "status", :string, :default => "open"
    t.column "error_message", :string
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

  create_table "publishers", :force => true do |t|
    t.column "name", :string, :default => "", :null => false
  end

  create_table "tags", :force => true do |t|
    t.column "name", :string, :default => "", :null => false
  end

  create_table "users", :force => true do |t|
    t.column "login", :string
    t.column "email", :string
    t.column "crypted_password", :string, :limit => 40
    t.column "salt", :string, :limit => 40
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
    t.column "remember_token", :string
    t.column "remember_token_expires_at", :datetime
    t.column "pw_reset_code", :string, :limit => 40
  end

end
