# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 6) do

  create_table "authors", :force => true do |t|
    t.column "first_name", :string
    t.column "last_name", :string
  end

  create_table "authors_books", :id => false, :force => true do |t|
    t.column "author_id", :integer, :default => 0, :null => false
    t.column "book_id", :integer, :default => 0, :null => false
  end

  add_index "authors_books", ["author_id"], :name => "fk_bk_authors"
  add_index "authors_books", ["book_id"], :name => "fk_bk_books"

  create_table "books", :force => true do |t|
    t.column "title", :string, :default => "", :null => false
    t.column "publisher_id", :integer, :default => 0, :null => false
    t.column "published_at", :datetime
    t.column "isbn", :string, :limit => 13
    t.column "blurb", :text
    t.column "page_count", :integer
    t.column "price", :float
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
    t.column "cover_image", :string
  end

  add_index "books", ["publisher_id"], :name => "fk_books_publishers"

  create_table "cart_items", :force => true do |t|
    t.column "book_id", :integer
    t.column "cart_id", :integer
    t.column "price", :float
    t.column "amount", :integer
    t.column "created_at", :datetime
  end

  create_table "carts", :force => true do |t|
  end

  create_table "publishers", :force => true do |t|
    t.column "name", :string, :default => "", :null => false
  end

end
